# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Thu Nov 18 10:11:02 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(695, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 581, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_kml2shp = QtWidgets.QWidget()
        self.tab_kml2shp.setObjectName("tab_kml2shp")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_kml2shp)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 551, 301))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.kml_file_list = QtWidgets.QTextBrowser(self.layoutWidget_4)
        self.kml_file_list.setDocumentTitle("")
        self.kml_file_list.setObjectName("kml_file_list")
        self.verticalLayout_3.addWidget(self.kml_file_list)
        self.tabWidget.addTab(self.tab_kml2shp, "")
        self.tab_shp2kml = QtWidgets.QWidget()
        self.tab_shp2kml.setObjectName("tab_shp2kml")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_shp2kml)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 551, 301))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.shp_file_list = QtWidgets.QTextBrowser(self.layoutWidget_3)
        self.shp_file_list.setDocumentTitle("")
        self.shp_file_list.setObjectName("shp_file_list")
        self.verticalLayout_2.addWidget(self.shp_file_list)
        self.tabWidget.addTab(self.tab_shp2kml, "")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 400, 631, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(110, 370, 481, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(10, 370, 91, 21))
        self.label_status.setObjectName("label_status")
        self.label_gdal2 = QtWidgets.QLabel(self.centralwidget)
        self.label_gdal2.setGeometry(QtCore.QRect(108, 432, 41, 41))
        self.label_gdal2.setText("")
        self.label_gdal2.setPixmap(QtGui.QPixmap("img/abaeicon.jpg"))
        self.label_gdal2.setObjectName("label_gdal2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 430, 481, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_exit = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout.addWidget(self.btn_exit, 0, 1, 1, 1)
        self.btn_change_theme = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_change_theme.setObjectName("btn_change_theme")
        self.gridLayout.addWidget(self.btn_change_theme, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(5, 432, 91, 40))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(600, 40, 87, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_search = QtWidgets.QPushButton(self.widget)
        self.btn_search.setIconSize(QtCore.QSize(32, 32))
        self.btn_search.setObjectName("btn_search")
        self.verticalLayout.addWidget(self.btn_search)
        self.btn_clear = QtWidgets.QPushButton(self.widget)
        self.btn_clear.setIconSize(QtCore.QSize(32, 32))
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout.addWidget(self.btn_clear)
        self.btn_accept = QtWidgets.QPushButton(self.widget)
        self.btn_accept.setIconSize(QtCore.QSize(32, 32))
        self.btn_accept.setObjectName("btn_accept")
        self.verticalLayout.addWidget(self.btn_accept)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 695, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAutores = QtWidgets.QAction(MainWindow)
        self.actionAutores.setObjectName("actionAutores")
        self.actionClasificar = QtWidgets.QAction(MainWindow)
        self.actionClasificar.setObjectName("actionClasificar")
        self.actionBuscar = QtWidgets.QAction(MainWindow)
        self.actionBuscar.setObjectName("actionBuscar")
        self.actionLicencia = QtWidgets.QAction(MainWindow)
        self.actionLicencia.setObjectName("actionLicencia")
        self.actionAcerca_de_Qt = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de_Qt.setObjectName("actionAcerca_de_Qt")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAuthors = QtWidgets.QAction(MainWindow)
        self.actionAuthors.setObjectName("actionAuthors")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionthird_party = QtWidgets.QAction(MainWindow)
        self.actionthird_party.setObjectName("actionthird_party")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionAuthors)
        self.menuHelp.addAction(self.actionLicense)
        self.menuHelp.addAction(self.actionthird_party)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "KmlShpConvert", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Archivo(s) KML:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kml2shp), QtWidgets.QApplication.translate("MainWindow", "KML to SHP", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Archivo(s) SHP:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_shp2kml), QtWidgets.QApplication.translate("MainWindow", "SHP to KML", None, -1))
        self.label_status.setText(QtWidgets.QApplication.translate("MainWindow", "Ready", None, -1))
        self.btn_exit.setText(QtWidgets.QApplication.translate("MainWindow", "Salir", None, -1))
        self.btn_change_theme.setText(QtWidgets.QApplication.translate("MainWindow", "Cambiar Tema", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Powered by", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "GDAL", None, -1))
        self.btn_search.setText(QtWidgets.QApplication.translate("MainWindow", "Buscar", None, -1))
        self.btn_clear.setText(QtWidgets.QApplication.translate("MainWindow", "Limpiar", None, -1))
        self.btn_accept.setText(QtWidgets.QApplication.translate("MainWindow", "Aceptar", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionAutores.setText(QtWidgets.QApplication.translate("MainWindow", "Autores", None, -1))
        self.actionClasificar.setText(QtWidgets.QApplication.translate("MainWindow", "Clasificar", None, -1))
        self.actionBuscar.setText(QtWidgets.QApplication.translate("MainWindow", "Buscar", None, -1))
        self.actionLicencia.setText(QtWidgets.QApplication.translate("MainWindow", "Licencia", None, -1))
        self.actionAcerca_de_Qt.setText(QtWidgets.QApplication.translate("MainWindow", "Acerca de Qt", None, -1))
        self.actionAbout_Qt.setText(QtWidgets.QApplication.translate("MainWindow", "Acerca de Qt", None, -1))
        self.actionAuthors.setText(QtWidgets.QApplication.translate("MainWindow", "Autores", None, -1))
        self.actionLicense.setText(QtWidgets.QApplication.translate("MainWindow", "Licencia", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "Acerca de", None, -1))
        self.actionthird_party.setText(QtWidgets.QApplication.translate("MainWindow", "Third party", None, -1))

