# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(695, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 581, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_kml2shp = QtWidgets.QWidget()
        self.tab_kml2shp.setObjectName("tab_kml2shp")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_kml2shp)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 551, 311))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.kml_file_list = QtWidgets.QTextBrowser(self.layoutWidget_4)
        self.kml_file_list.setDocumentTitle("")
        self.kml_file_list.setObjectName("kml_file_list")
        self.verticalLayout_3.addWidget(self.kml_file_list)
        self.tabWidget.addTab(self.tab_kml2shp, "")
        self.tab_shp2kml = QtWidgets.QWidget()
        self.tab_shp2kml.setObjectName("tab_shp2kml")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_shp2kml)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 551, 311))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.shp_file_list = QtWidgets.QTextBrowser(self.layoutWidget_3)
        self.shp_file_list.setDocumentTitle("")
        self.shp_file_list.setObjectName("shp_file_list")
        self.verticalLayout_2.addWidget(self.shp_file_list)
        self.tabWidget.addTab(self.tab_shp2kml, "")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 400, 631, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(600, 40, 87, 146))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_search = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_search.setIconSize(QtCore.QSize(32, 32))
        self.btn_search.setObjectName("btn_search")
        self.verticalLayout.addWidget(self.btn_search)
        self.btn_clear = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_clear.setIconSize(QtCore.QSize(32, 32))
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout.addWidget(self.btn_clear)
        self.btn_accept = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_accept.setIconSize(QtCore.QSize(32, 32))
        self.btn_accept.setObjectName("btn_accept")
        self.verticalLayout.addWidget(self.btn_accept)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(110, 370, 481, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(10, 370, 91, 21))
        self.label_status.setObjectName("label_status")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(108, 432, 41, 41))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("img/abaeicon.jpg"))
        self.label_6.setObjectName("label_6")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(170, 430, 481, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_exit = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout.addWidget(self.btn_exit, 0, 1, 1, 1)
        self.btn_change_theme = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_change_theme.setObjectName("btn_change_theme")
        self.gridLayout.addWidget(self.btn_change_theme, 0, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(5, 432, 91, 40))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 695, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAutores = QtWidgets.QAction(MainWindow)
        self.actionAutores.setObjectName("actionAutores")
        self.actionClasificar = QtWidgets.QAction(MainWindow)
        self.actionClasificar.setObjectName("actionClasificar")
        self.actionBuscar = QtWidgets.QAction(MainWindow)
        self.actionBuscar.setObjectName("actionBuscar")
        self.actionLicencia = QtWidgets.QAction(MainWindow)
        self.actionLicencia.setObjectName("actionLicencia")
        self.actionAcerca_de_Qt = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de_Qt.setObjectName("actionAcerca_de_Qt")
        self.about_qt = QtWidgets.QAction(MainWindow)
        self.about_qt.setObjectName("about_qt")
        self.authors = QtWidgets.QAction(MainWindow)
        self.authors.setObjectName("authors")
        self.license = QtWidgets.QAction(MainWindow)
        self.license.setObjectName("license")
        self.version = QtWidgets.QAction(MainWindow)
        self.version.setObjectName("version")
        self.menuHelp.addAction(self.version)
        self.menuHelp.addAction(self.about_qt)
        self.menuHelp.addAction(self.authors)
        self.menuHelp.addAction(self.license)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KmlShpConvert"))
        self.label_5.setText(_translate("MainWindow", "Archivo(s) KML:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kml2shp), _translate("MainWindow", "KML to SHP"))
        self.label_2.setText(_translate("MainWindow", "Archivo(s) SHP:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_shp2kml), _translate("MainWindow", "SHP to KML"))
        self.btn_search.setText(_translate("MainWindow", "Buscar"))
        self.btn_clear.setText(_translate("MainWindow", "Limpiar"))
        self.btn_accept.setText(_translate("MainWindow", "Aceptar"))
        self.label_status.setText(_translate("MainWindow", "Ready"))
        self.btn_exit.setText(_translate("MainWindow", "Salir"))
        self.btn_change_theme.setText(_translate("MainWindow", "Cambiar Tema"))
        self.label_3.setText(_translate("MainWindow", "Powered by"))
        self.label_7.setText(_translate("MainWindow", "GDAL"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAutores.setText(_translate("MainWindow", "Autores"))
        self.actionClasificar.setText(_translate("MainWindow", "Clasificar"))
        self.actionBuscar.setText(_translate("MainWindow", "Buscar"))
        self.actionLicencia.setText(_translate("MainWindow", "Licencia"))
        self.actionAcerca_de_Qt.setText(_translate("MainWindow", "Acerca de Qt"))
        self.about_qt.setText(_translate("MainWindow", "Acerca de Qt"))
        self.authors.setText(_translate("MainWindow", "Autores"))
        self.license.setText(_translate("MainWindow", "Licencia"))
        self.version.setText(_translate("MainWindow", "Version"))
